title: Flickr Photos
tagline: The bot shows you photos from flickr for a given location or person.
author:
  name : Recime Inc
  url : "https://recime.io"

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

sass:
    sass_dir: _sass
